version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-repository
    ports:
      - "8081:8081" # Expose the Nexus UI on port 8081
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2048m -XX:MaxDirectMemorySize=2G
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local
